[package]
name = "sm"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }

sysinfo = "0.36.1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
